### PR TITLE
Allow SIGHUP or custom signals for --restart option

### LINKED ISSUE #41: Allow SIGHUP or custom signals for --restart option
Sometimes it's sufficient to send `SIGHUP` to a process upon file changes. 

In my case, I'm watching SSL certificates and the daemon in question can reload certificates using `SIGHUP`. A `SIGTERM` would interrupt services.

I'll take a shoot at a pull-request, if you think this would benefit others as well.

### PR DESCRIPTION
**Pull request by chr4**
Sometimes it's sufficient to send SIGHUP to a process upon file changes.

In my case, I'm watching SSL certificates and the daemon in question can reload certificates using SIGHUP. A SIGTERM would interrupt services.

This pull-request implements a `--hup` flag (short: `-g`) analogue to the `--kill` flag.

This fixes #41

### CODE REVIEW

**Comment by mattgreen** [comment]
Thanks for submitting! This looks good to me other than the lack of a `hup` fn for the Windows version of `Process`. Please add that so CI passes.

Are there any other signals one would want to send to a process other than `SIGHUP`, `SIGTERM` and `SIGKILL`? I can't think of others. Only reason I mention is whether it is worth generalizing these to `--restart SIGHUP`.

**Comment by chr4** [comment]
Wow, that was fast feedback!

There's more I think: Other examples would be `SIGUSR1` and `SIGUSR2` (sometimes used by daemons for specific actions).

My patch is a quick solution that works for me, but I think that in the long run a signal flag like `--signal SIGHUP` would be a clean, versatile and convenient option (defaulting to `SIGTERM`).
Using an additional argument on `--restart` as you've proposed would also work.

**Comment by chr4** [comment]
Regarding the windows fix: I'm not sure what the `SIGHUP` equivalent in Windows would be, to be honest. I could implement a dummy `pub fn hup`, but that seems a little dirty. 

Let me know which way you want to go - In case we specify the signal explicitly, this wouldn't affect the Windows version, would it?

**Comment by mattgreen** [comment]
I like the idea of supporting `SIGUSR1` and friends now, rather than later, especially with a `--signal` argument. My current line of thinking:

1. Add `--signal` arg, with whitelist of allowed signal names (SIGKILL, SIGTERM, etc).
2. Change `Process` to have a single method, `signal(sig: &str)`, which handles all signals for a given implementation.
3. Windows: ignore the `sig` argument and just terminate the process, as it [doesn't support most signals](https://msdn.microsoft.com/en-us/library/xdkz3x12.aspx) anyway.

`sig` should probably be its own type, as well, to avoid the joys of stringly typed programming.

This is expanding the scope of this a bit. If you'd like me to do this, just let me know. Or if you'd like to tackle it, then go for it!

**Comment by chr4** [comment]
My thoughts

1. Not sure what you mean with "whitelisting". I was thinking to just use the given signal instead of `SIGTERM`
2. Exactly
3. Sounds good to me

I can give it a go if you're busy at the moment. I'm sure you'd be a lot quicker in implementing it, but I'm willing to contribute more code if it makes sense! Let me know what you think.

Currently, I'm trying to figure out `signal.rs` :)

**Comment by mattgreen** [comment]
> Not sure what you mean with "whitelisting"

Should have explained more: in `cli.rs` we parse the command line args using `clap`. I believe there's a way to list only the valid arguments for it so we catch typos immediately.

I'm working on other things at the moment, so have it. Let me know if I can help you though!

**Comment by chr4** [comment]
Closing this in favor of https://github.com/mattgreen/watchexec/pull/43

**Pull request closed without merging**
