### PR TITLE
Add support for --no-shell option

### PR DESCRIPTION
**Pull request by chr4**
As it seems like adding more options to `watchexec` is my hobby, here's the next one! :)

This pull-request adds the `--no-shell` option, which when activated executes the `<command>` directly, instead of wrapping it in `sh -c ''`.

This is useful in a few scenarios:
- It's a little faster then spawning `sh`
- When using daemons and `--signal` is used, the signal is received directly by the process.

Note: I'm not extremely happy with all of my code, especially with [these lines](https://github.com/mattgreen/watchexec/compare/master...chr4:no_shell?expand=1#diff-02ead270dd1dae475907f3d17c29f26eR33) but I didn't manage to find a more elegant version. I'm really looking forward to feedback here!

### CODE REVIEW

**Comment by mattgreen** [comment]
Overall it looks fine. I don't know enough Rust to give you a better idiom than what you did for the requested lines. I do think the lines around the `split_whitespace()` call are not quite idiomatic. Perhaps rust-clippy could suggest something better?

**Comment by chr4** [comment]
Thanks for the hint with rust-clippy! It complained about two other incidences (boolean-match and useless `format!()` (corrected in the latest two commits) but couldn't help me with the `split_whitespace()` issues.

I'm trying to get some feedback on this issue from [reddit](https://www.reddit.com/r/rust/comments/64ic0q/idiomatic_string_processing/).

**Comment by chr4** [comment]
Thanks to [burntsushi](https://www.reddit.com/user/burntsushi) from `/r/rust` I've came up with the following solution (which looks very clean to me): f88f1b3

**Comment by mattgreen** [comment]
Looks great. I'm going to merge this and look to put out the next version sometime this week.

**Pull request merged**
