### PR TITLE
Creating method to update the watch_exec variable with the greatest c…

### PR DESCRIPTION
**Pull request by craftytrickster**
https://github.com/mattgreen/watchexec/issues/19

I am not thrilled about using Rcs and RefCells here, but I couldn't get it to compile otherwise.

### CODE REVIEW

**Comment by mattgreen** [comment]
This looks good.

Since we are post-1.0, let's define a new env var called $WATCHEXEC_COMMON_PATH that contains this, and leave $WATCHEXEC_UPDATED_PATH for simple use cases.

What platform have you tried this on? I'd like to make sure I test it manually on all three platforms.

**Comment by craftytrickster** [comment]
I've added back support for the `$WATCHEXEC_UPDATED_PATH` as requested. I have successfully tested this on Linux.

**Comment by mattgreen** [comment]
Great, will accept this and start testing it.

**Comment by mattgreen** [comment]
Excellent work on this. I profiled this by monitoring my entire drive while deleting 20,000 files and it didn't even bat an eye.

**Pull request merged**
